services:
  app:
    build: .
    expose:
      - 8000
    environment:
      - REDIS_URL=redis://valkey:6379/0
    volumes:
      - ./storage:/app/storage
    depends_on:
      - valkey
    restart: on-failure
    networks:
      - raven-net

  valkey:
    image: valkey/valkey:9-alpine
    expose:
      - 6379
    networks:
      - raven-net

networks:
  raven-net:
    driver: bridge
